### ISSUE TITLE
SC: Voucher

### ISSUE THREAD

**Issue by vMysterion** [Software-Projekt-Thiel-2020/Backend#15]
Smart Contracts about the Use Case of Voucher (3.1.2 Use Case: Gutscheine) of the Specificationsbook
Please take information from that source.

**Comment by JulianWasilewski** [comment]
Der Use Case Gutscheine ist im vergleich zu dem Use Case Spenden nur rudimentär beschrieben. Würde das beim nächsten Meeting genauer spezifizieren und danach den Smart Contract dafür schreiben.
