### ISSUE TITLE
Datumsangaben für eine Spende und Kauf eines Gutscheins

### ISSUE THREAD

**Issue by dermodmaster** [Software-Projekt-Thiel-2020/Backend#169]
Hallo,
wir haben ja die Portfolioseite wo man sieht, welche Gutscheine man besitzt und welche Spenden man getätigt hat. Man kann die Spenden leider zeitlich nicht auseinander halten, sowie auch die Gutscheine. Wäre irgendwie cooler, wenn man dort auch sehen kann, wann man gespendet oder gekauft hat.
Lässt sich das einrichten?

**Comment by vMysterion** [comment]
Aber sicher lässt sich das einrichten, Levent.
