### ISSUE TITLE
DB: Credentials + schema.sql

### ISSUE THREAD

**Issue by Alizame** [Software-Projekt-Thiel-2020/Backend#17]
So, wo es hier endlich die ersten commits gibt, kann ich ja gleich die Qualität prüfen...

- Im init sql Script einen Account fürs backend erstellen, der auf eine DB beschränkt ist (also mit entsprechenden Permissions).
root ist irgendwie zu root... 
- Und wenn wir schon dabei sind: der Name 'mydb' ist etwas ungenau vielleicht.
- Das schema.sql scheint wohl nichts für MariaDB zu sein (zumindest nicht für version 10.1.44 aus den Ubuntu-Paketquellen):
ERROR 1064 (42000) at line 34 in file: 'schema.sql': You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '
  CONSTRAINT `fk_Institution_1`
    FOREIGN KEY (`fkSmartContractInstitution`)
' at line 7
.....

Ich weiß das Ganze ist noch extrem frisch und die ersten commits überhaupt, aber das sind schon mal meine 2 cent dazu.

PS: Ist SQLAlchemy noch im Rennen?
PPS: Ihr könnt in den commit-Nachrichten entsprechende Issues (also #17 bspw.) erwähnen, dann taucht das da auch auf

**Comment by CrappyAlgorithm** [comment]
- Die Accounterstellung werde ich mit einbauen, hatte die nur erstmal weggelassen, da mir dies in dem frühen stand der Testumgebung noch unwichtig erschien.
- Der Datenbankname sollte am besten im Datenbankschema angepasst werden. Da das Script generiert ist, müsste man das sonnst bei der nächsten Änderung wieder manuell machen.
- Das schema.sql Skript hatte ich nun  nur unter MariaDB Version 10.5.3 getestet und da funktionierte es.
- Zu SQLAlchemy habe ich das nun so verstanden, das wir das leider nicht verwenden.

**Comment by Alizame** [comment]
- Top
- Tatsächlich geht das erst mit dem Release Candidate von [MariaDB ](https://downloads.mariadb.org/mariadb/+releases/)(10.5.3), mit der neuesten Stable geht es nicht (10.4.13).
Ist natürlich etwas unschön, aber wenn wir das Skript generieren lassen haben wir wohl keine Wahl
- Big oof zu kein SQLAlchemy von mir.
