### ISSUE TITLE
Problem beim Meilensteinvoting

### ISSUE THREAD

**Issue by dermodmaster** [Software-Projekt-Thiel-2020/Backend#215]
Hallo, ich habe eine Spende erstellt mit dem Header voteEnabled: 1

Danach wollte ich voten, aber das Backend meldet: {"error":"didn't register to vote"}. Wird Vote Enabled für die Donation in der DB korrekt abgespeichert? Irgendwas passt nicht.

**Comment by Alizame** [comment]
API Missverständnis, fixed
