### ISSUE TITLE
GET /donations: Fehlende Info für Meilensteinvoting: voteEnabled

### ISSUE THREAD

**Issue by dermodmaster** [Software-Projekt-Thiel-2020/Backend#216]
Hallo ich rufe meine Donations auf (https://spenderschlender-backend.de/api/donations?iduser=13) allerdings findet sich in den Daten keine Information darüber, ob für die Spende das Voting überhaupt aktiviert wurde. (voteEnabled) 

Das bräuchte ich noch. Entweder als separates Attribut oder man könnte sich darauf einigen, dass voted dann -1 ist.

**Comment by Alizame** [comment]
Separates Attribut!

Levent K. <notifications@github.com> schrieb am Di., 4. Aug. 2020, 13:19:
