### ISSUE TITLE
GET Project: positive und negative Stimmenanzahl mitgeben

### ISSUE THREAD

**Issue by Alizame** [Software-Projekt-Thiel-2020/Backend#227]

**Comment by nesti024** [comment]
Projects an sich haben doch keine Stimmzahlen sondern nur die Milestones, oder?
Außerdem werden in der Datenbank keine positiven Votes gespeichert.
Stimmt das..? Dann würde dieses Issue doch wegfallen da man die Votes direkt über die Milestones bezieht?

**Comment by Alizame** [comment]
War vielleicht etwas schwammig formuliert:
Es geht darum, das diese infos bei den Meilensteinen nicht mitgeliefert werden

**Comment by nesti024** [comment]
Werden sie doch. Unter <base>/api/projects/<id> hat jeder Milestone currentVotes. Das sind alle positiven Stimmen minus der negativen. Oder ist hier was anderes gemeint?
