### ISSUE TITLE
Prospector: code linting fixes

### ISSUE THREAD

**Issue by maxkleinke** [Software-Projekt-Thiel-2020/Backend#26]
#25 implementiert code linting. Derzeit schlägt der Durchlauf noch fehl, weil einige Codezeilen als fehlerhaft angezeigt werden. 

Actions -> All workflows -> QA: Code Linting, Static Analysis, Security Analysis -> prospector für eine Übersicht der zu fixenden Codezeilen (downloaden und manuelles Ausführen ist natürlich auch möglich).

**Comment by Alizame** [comment]
done #27
