### ISSUE TITLE
db credentials leaked

### ISSUE THREAD

**Issue by maxkleinke** [Software-Projekt-Thiel-2020/Backend#28]
Das Software-Projekt ist auf github public. Jeder Benutzer kann unter backend/util/db.py die login credentials unserer Datenbank einsehen

Mögliche Lösung: Einbinden einer externen config die direkt auf dem backend definiert wird

**Comment by Alizame** [comment]
Well yes, but actually no.

Der Host ist in dem Fall ja der localhost, aber ansich hast du Recht. 

Ich wollte sowieso bald eine config-Datei einführen und die danach in die .gitignore packen, damit jeder seine eigene config hat ohne das die im Repo landet.

**Comment by Alizame** [comment]
#27 fixed
