### ISSUE TITLE
DB+RESTAPI: file upload/access

### ISSUE THREAD

**Issue by dermodmaster** [Software-Projekt-Thiel-2020/Backend#59]
Am besten wäre es, wir bekommen in den erwähnten Routen zusätzlich noch eine URL zu nem quadratischen Projektbild oder Logo des Projekts für die Auflistung aller Projekte und Institutionen

**Comment by dermodmaster** [comment]
+ zusätzlich bräuchten wir dann noch eine Funktion um diese Bilder hochzuladen

**Comment by Alizame** [comment]
siehe https://flask.palletsprojects.com/en/1.1.x/patterns/fileuploads/ falls sowas benötigt werden sollte.
