### ISSUE TITLE
REST-API: Donations

### ISSUE THREAD

**Issue by dermodmaster** [Software-Projekt-Thiel-2020/Backend#63]
REST-API: GET /donations liefert keinen Bezug zu einem Spendenprojekt

Also für die Übersicht aller getätigten Spenden wäre es cool, wenn man auch in der Rückantwort zusätzlich den Namen+ID des Projekts bekommen könnte.

**Comment by vMysterion** [comment]
EtherAccountKey aus dem API Call entfernen
