### ISSUE TITLE
REST-API: GET /vouchers - Name der Institution bitte mitsenden

### ISSUE THREAD

**Issue by dermodmaster** [Software-Projekt-Thiel-2020/Backend#64]
REST-API: GET /vouchers - Name der Institution bitte mitsenden

Also für die Übersicht aller Gutscheine wäre es cool, wenn man auch in der Rückantwort zusätzlich zur **institutionid** den Namen der Institution bekommen könnte.

**Comment by vMysterion** [comment]
@Batschko
