### ISSUE TITLE
Setup production enviorment

### ISSUE THREAD

**Issue by vMysterion** [Software-Projekt-Thiel-2020/Backend#8]
Setup Raspberry Pi with enviorment to run the backend

**Comment by CrappyAlgorithm** [comment]
explanation to connection was added to the Readme.md

**Comment by Alizame** [comment]
Man kann sich per SSH verbinden, es läuft auch ein MariaDB-Server (version 10.3.22).
- allerdings ist für diesen kein Port freigegeben. Absicht?
- sicher das sich die IP nicht ändert, sondern statisch ist? Kenne mich mit Unitymedia/Vodafone jetzt nicht so aus.

Und am wichtigsten:
- sollten wir bei SSH statt Passwort auf Public/Private Key Authentifizierung setzen? Das Ding hängt schließlich im Internet und **dieses Repo ist ÖFFENTLICH EINSEHBAR** => also **NIEMALS** PWs/Zertifikate über github verteilen!

**Comment by CrappyAlgorithm** [comment]
Ok das mit dem SSH Zugang ist eine gute Anmerkung, ich werde mir das mal anschauen und ändern.
- Für die Datenbank ist tatsächlich absichtlich noch kein Zugriff eingerichtet, kann ich aber noch hinzufügen wenn benötigt.
- Die IP wird sich tatsächlich nicht ändern, solange der Router nicht länger als 30 Minuten vom Strom genommen wird.
