### ISSUE TITLE
RESTAPI: POST /donation - etherAccountKey muss raus!

### ISSUE THREAD

**Issue by dermodmaster** [Software-Projekt-Thiel-2020/Backend#83]
RESTAPI: POST /donation - Attribut etherAccountKey wird fälschlicherweise immer noch vom Backend erwartet und muss raus...

**Comment by dermodmaster** [comment]
#63 wurde fälschlicherweise geschlossen

**Comment by Talinx** [comment]
Ist aus der API-Spezifikation jetzt raus.
