### ISSUE TITLE
SQL Script ER

### ISSUE THREAD

**Issue by vMysterion** [Software-Projekt-Thiel-2020/Backend#9]
SQL Script to create Database from the ER script

Please add some testdata too.

**Comment by Talinx** [comment]
Eine Möglichkeit ist, es zu generieren:
[MySQL-Worbench-Datei](https://github.com/Software-Projekt-Thiel-2020/Orga-Stuff/blob/master/Anforderungen/Weiteres/datenbankmodell.mwb) mit [MySQL Workbench](https://www.mysql.com/products/workbench/) öffnen -> File -> Export -> Forward Engineer SQL Create Script.
